In [1]:
print('d')

d


## 마크다운 
마크다운 = 주석이랑 같다고 보면된다
///

## 마크다운
a = 선택한 셀 위에 새로운 셀 삽입\
b = 선택한 셀 아래에 새로운 셀 삽입

In [2]:
a = 10

In [3]:
print(a)


10


In [ ]:
a

In [4]:
b = '1-2-3-4-5'

In [5]:
b

'1-2-3-4-5'

In [6]:
b[1::3]

'-3-'

In [7]:
b[0::2]

'12345'

In [8]:
b[::-2]

'54321'

In [9]:
'-'.join('HelloWorldPython')

'H-e-l-l-o-W-o-r-l-d-P-y-t-h-o-n'

In [10]:
'-'.join('12345')

'1-2-3-4-5'

In [11]:
'Hello-World-Python'.split('-')

['Hello', 'World', 'Python']

In [12]:
'서울시 마포구 상암동 1585'.split()

['서울시', '마포구', '상암동', '1585']

In [13]:
text = '\t 문자열 정리 \n'

In [14]:
text.strip()

'문자열 정리'

In [15]:
생일 = '2016/08/30'

In [16]:
생일.replace('/', '-')

'2016-08-30'

In [17]:
'Hello World Python'.startswith('Hello')

True

In [18]:
'Hello World Python'.endswith('Python')

True

In [19]:
'Python' in 'Hello World Python'

True

In [20]:
'Java' in 'Hello World Python'

False

In [21]:
'{}, {:f}, {:.1f}, {:.2f}, {:.2%}'.format(3, 3, 3, 3.1475, 1/3)

'3, 3.000000, 3.0, 3.15, 33.33%'

In [22]:
jan, dec = 1, 12

In [24]:
print("한 해의 시작은 {:03d}월".format(jan))

한 해의 시작은 001월


In [25]:
text = "Hello World Python"
text.count('o')

3

In [26]:
text = 'Hello World Python, Welcome to Python World'
text.count('Python')

2

In [27]:
text.index('o')

4

In [28]:
text.find('Python')

12

In [29]:
text.find('Python', 20)

31

In [30]:
'Hello World'.capitalize()

'Hello world'

In [31]:
'Hello World'.lower()

'hello world'

In [32]:
'Hello World'.upper()

'HELLO WORLD'

In [33]:
a = 0
while a < 5 :
    print(a, '반복합니다')
    a += 1

0 반복합니다
1 반복합니다
2 반복합니다
3 반복합니다
4 반복합니다


In [34]:
for a in range(0, 5) :
    print(a, '반복합니다.')

0 반복합니다.
1 반복합니다.
2 반복합니다.
3 반복합니다.
4 반복합니다.


In [35]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [36]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [38]:
list(range(0, 10, 2))

[0, 2, 4, 6, 8]

In [39]:
list(range(1, 10, 2))

[1, 3, 5, 7, 9]

In [40]:
list(range(10, 0))

[]

In [41]:
list(range(10, 0, -1))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [42]:
list(range(10, 0, -2))

[10, 8, 6, 4, 2]

In [43]:
list(range(10, 0, -3))

[10, 7, 4, 1]

In [44]:
num = list(range(1, 11))

In [45]:
for i in num :
    print(i)

1
2
3
4
5
6
7
8
9
10


In [46]:
num = 3
for i in range(1, 10):
    answer = num * i
    print(f'{num} * {i} = {answer}')

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27


In [47]:
def square(x, y):
    x = x**2
    y = y**2
    return x, y

In [48]:
a,b = square(2, 3)
print(a)
print(b)

4
9


In [49]:
letters = ['A', 'B', 'C', 'D', 'E', 'F']
letters

['A', 'B', 'C', 'D', 'E', 'F']

In [50]:
letters[1]

'B'

In [51]:
letters[0]

'A'

In [52]:
letters[5]

'F'

In [55]:
letters.append('a')

In [56]:
letters

['A', 'B', 'C', 'D', 'E', 'F', 'a', 'a']

In [57]:
letters.count('a')

2

In [58]:
letters.insert(2, 'z')
letters

['A', 'B', 'z', 'C', 'D', 'E', 'F', 'a', 'a']

In [59]:
letters.pop(2)
letters

['A', 'B', 'C', 'D', 'E', 'F', 'a', 'a']

In [62]:
letters.remove('a')
letters

ValueError: list.remove(x): x not in list

In [63]:
letters

['A', 'B', 'C', 'D', 'E', 'F']

In [64]:
letters.sort(reverse=True)

In [65]:
letters

['F', 'E', 'D', 'C', 'B', 'A']

In [66]:
letters.sort()
letters

['A', 'B', 'C', 'D', 'E', 'F']

In [69]:
my_dict = {"shirts": 5, "pants": 4, "shoes": 2}
print(my_dict["pants"])

4


In [70]:
my_list = range(10)
print(*filter(lambda x: x ** 2 / 3 < 5, my_list))

0 1 2 3


In [87]:
def print_star(x) :
    
    for i in range(0,x) :
        for j in range(0, x-i) :
            print("*", end="",)
        print()    
    

    

In [89]:
print_star(6)

******
*****
****
***
**
*


In [91]:
중간고사 = {
    "수학" : 100,
    "영어" : 90,
}
중간고사

{'수학': 100, '영어': 90}

In [92]:
중간고사['국아'] = 85
중간고사

{'수학': 100, '영어': 90, '국아': 85}

In [93]:
중간고사['영어']

90

In [94]:
list(중간고사.keys())

['수학', '영어', '국아']

In [95]:
list(중간고사.values())

[100, 90, 85]

In [96]:
for 과목, 점수 in 중간고사.items():
    print('{} 과목점수는 {} 점'.format(과목, 점수))

수학 과목점수는 100 점
영어 과목점수는 90 점
국아 과목점수는 85 점


In [97]:
중간고사['영어'] = 95
중간고사

{'수학': 100, '영어': 95, '국아': 85}

In [98]:
tuple1 = (1, 2, 3)
tuple1

(1, 2, 3)

In [99]:
tuple1[0] = 4

TypeError: 'tuple' object does not support item assignment

In [2]:
import numpy as np
a = []
for i in range(0, 100):
    a.append(i)
arr = np.array(a)
b = arr.reshape(10, 10)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [109]:


import numpy as np
a = []
for i in range(0, 10):
    
    for j in range(0, 10):
        a.append(0)
        for k in range(1, i+1):
                a[i*10+j] += 2**k
                a[i*10+j] += (2**(k-1))  
        
            
            
                
    
        a[i*10+j] += 2**i*j 
                 
arr = np.array(a)
    
b = arr.reshape(10, 10)
b

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [   3,    5,    7,    9,   11,   13,   15,   17,   19,   21],
       [   9,   13,   17,   21,   25,   29,   33,   37,   41,   45],
       [  21,   29,   37,   45,   53,   61,   69,   77,   85,   93],
       [  45,   61,   77,   93,  109,  125,  141,  157,  173,  189],
       [  93,  125,  157,  189,  221,  253,  285,  317,  349,  381],
       [ 189,  253,  317,  381,  445,  509,  573,  637,  701,  765],
       [ 381,  509,  637,  765,  893, 1021, 1149, 1277, 1405, 1533],
       [ 765, 1021, 1277, 1533, 1789, 2045, 2301, 2557, 2813, 3069],
       [1533, 2045, 2557, 3069, 3581, 4093, 4605, 5117, 5629, 6141]])

b[4:9]

In [98]:
b[0, 4:9]

array([4, 5, 6, 7, 8])

In [105]:
b[3:10, 6:10]

array([[  69,   77,   85,   93],
       [ 141,  157,  173,  189],
       [ 285,  317,  349,  381],
       [ 573,  637,  701,  765],
       [1149, 1277, 1405, 1533],
       [2301, 2557, 2813, 3069],
       [4605, 5117, 5629, 6141]])

In [117]:
import json

cities = [
    {'rank':1, 'city': {"학사" :'중문학',
                        "석사" : '컴퓨터공학',
                       
                       }, 'population': 24150000},
    {'rank': 2, 'city':'카라치', 'population': 23500000},
    {'rank': 3, 'city': '베이징', 'population': 215160000},
    {'rank': 4, 'city': '텐진', 'population': 14722100},
    {'rank': 5, 'city': '이스탄불', 'population':14160467},
]

In [118]:
with open('top_cities.json', 'w') as fw:
    json.dump(cities, fw)

In [119]:
with open('top_cities.json', 'r') as fr:
    json_file = json.load(fr)
    print(json_file)

[{'rank': 1, 'city': {'학사': '중문학', '석사': '컴퓨터공학'}, 'population': 24150000}, {'rank': 2, 'city': '카라치', 'population': 23500000}, {'rank': 3, 'city': '베이징', 'population': 215160000}, {'rank': 4, 'city': '텐진', 'population': 14722100}, {'rank': 5, 'city': '이스탄불', 'population': 14160467}]


In [121]:
import pandas as pd
import sqlite3
from pandas.io import sql
import os

DB_NAME = 'top_cities.db'
TABLE_NAME = 'TOP_CITIES'

def db_save(df, db_name, table_name):
    with sqlite3.connect(db_name) as con:
        try:
            df.to_sql(name = table_name, con = con, index = False, if_exists='append')
            
        except Excepton as e:
            print(str(e))
        print(len(df), '건 저장완료..')